---
title: "Gentrification Maps"
author: "Liam Purkey"
date: "2/28/2021"
output: html_document
---

```{r}
library(tidyverse)
library(readxl)
library(sf)
library(spData)
library(tmap)
library(extrafont)
source("/Users/liampurkey/Desktop/Honors/Code/R/Functions.R")
```

#Import Boundaries

```{r}
setwd("/Users/liampurkey/Desktop/Honors/RawDataFeb/Boundaries")
nyc_tracts = st_read("New York/New York.shp")
```

```{r}
nyc_tracts = nyc_tracts %>%
  mutate(City = "New York City") %>%
  mutate(State = "NY")
```

###Import and Clean Sample Data 

```{r}
setwd("/Users/liampurkey/Desktop/Honors/CleanDataFeb")
nyc_data = read_csv("New York/nyc_panel.csv")
```

```{r}
nyc_data = nyc_data %>%
  mutate(GEOID = as.character(GEOID)) %>%
  select(GEOID, City, State, edugentrify) %>%
  distinct()
```

###Merge Data with Shapefiles 

```{r}
nyc_map = left_join(nyc_tracts, nyc_data, by = c("GEOID", "City", "State"))
```

```{r}
nyc_map = nyc_map %>%
  mutate(edugentrify = case_when(is.na(edugentrify) ~ 0,
                                 edugentrify == 0 ~ 1,
                                 edugentrify == 1 ~ 2))
```

###Create Maps 

```{r}
nyc_out = tm_shape(nyc_map) + tm_polygons("edugentrify", style = "cat", palette = c("#DEEBF7", "#FDBEB9", "red4"),
                                labels = c("Not in Sample", "Not Gentrifying", "Gentrifying"),
                                title = "Legend") + 
                    tm_layout(legend.outside = TRUE, legend.text.size = .8, legend.title.size = 1, fontfamily = "Palatino", frame = FALSE,
                              asp = 1)
```

#Write Maps

```{r}
setwd("/Users/liampurkey/Desktop/Honors/Results/Maps")
tmap_save(tm = nyc_out, filename = "New York/nta_map.png")
```





