---
title: "Share Black Estimates"
author: "Liam Purkey"
date: "4/2/2021"
output: html_document
---

```{r}
library(tidyverse)
library(readxl)
library(CVXR)
library(hdm)
library(plm)
library(synthdid)
library(janitor)
library(xtable)
source("/Users/liampurkey/Desktop/Honors/Code/R/Functions.R")
source("/Users/liampurkey/Desktop/Honors/Code/R/SDD/sdd.regularization.R")
source("/Users/liampurkey/Desktop/Honors/Code/R/SDD/sdd.unitweights.R")
source("/Users/liampurkey/Desktop/Honors/Code/R/SDD/sdd.timeweights.R")
source("/Users/liampurkey/Desktop/Honors/Code/R/SDD/sdd.utils.R")
source("/Users/liampurkey/Desktop/Honors/Code/R/SDD/sdd.estimate.R")
```

#Import and Prepare Data 

```{r}
nyc_data = read_csv("/Users/liampurkey/Desktop/Honors/CleanDataFeb/New York/nyc_panel.csv") %>% 
  spread.variables(variable = "d_w_midwage", years = c(2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009), unit_var = "GEOID", time_var = "year", data = .)
```

```{r}
post_data = nyc_data %>%
  spread.variables(variable = "d_od_services", years = c(2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010), unit_var = "GEOID", time_var = "year", data = .) %>%
  spread.variables(variable = "d_od_midwage", years = c(2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010), unit_var = "GEOID", time_var = "year", data = .) %>%
  spread.variables(variable = "d_w_midwage", years = c(2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010), unit_var = "GEOID", time_var = "year", data = .) %>%
  filter(year >= 2011) %>%
  group_by(GEOID) %>%
  mutate(d_od_services_post = mean(d_od_services)) %>%
  mutate(d_od_midwage_post = mean(d_od_midwage)) %>%
  ungroup() %>%
  filter(year == 2018)
```

#Interaction Jackknife

```{r}
jackknife.interaction = function(outcome, treatment_var, interaction_var, unit_var, time_var, tau_hat, interaction_hat, data) {
  
  units = data %>%
    dplyr::distinct(!!as.name(unit_var)) %>%
    as.matrix() %>%
    as.vector()
  
  jackknife_interactions = c()
  jackknife_taus = c()
  
  for (i in 1:length(units)) {
    
    jackknife_data = data %>%
      dplyr::filter(!!as.name(unit_var) != units[i])
    
    jackknife_model = plm(paste(outcome, paste(treatment_var, paste(treatment_var, interaction_var, sep = "*"), sep = "+"), sep = "~"), 
                                model = "within", effect = "twoways", index = c(unit_var, time_var), weights = reg_weight, data = jackknife_data)
    
    jackknife_tau = jackknife_model$coefficients[1]
    jackknife_interaction = jackknife_model$coefficients[2]
    
    jackknife_taus = append(jackknife_taus, jackknife_tau)
    jackknife_interactions = append(jackknife_interactions, jackknife_interaction)
      
  }
  
  #Calculate Tau Variance
  tau_vector = rep(tau_hat, length(units))
  tau_variance = ((length(units) - 1)/length(units)) * sum((jackknife_taus - tau_vector)^2)
  
  #Calculate Interaction Variance
  interaction_vector = rep(interaction_hat, length(units))
  interaction_variance = ((length(units) - 1)/length(units)) * sum((jackknife_interactions - interaction_vector)^2)
  
  #Calculate t-statistics
  tau_t = tau_hat / sqrt(tau_variance)
  interaction_t = interaction_hat / sqrt(interaction_variance)
  
  #Calculate Degrees of Freedom
  df = nrow(data) - (nrow(unique(data %>% dplyr::select(all_of(unit_var)) %>% as.matrix)) - 1) - 
      (nrow(unique(data %>% dplyr::select(all_of(time_var)) %>% as.matrix)) - 1) - 2
  
  #Calculate p-values 
  tau_p = stats::pt(-abs(tau_t), df = df, lower.tail = TRUE) + stats::pt(abs(tau_t), df = df, lower.tail = FALSE)
  interaction_p = stats::pt(-abs(interaction_t), df = df, lower.tail = TRUE) + stats::pt(abs(interaction_t), df = df, lower.tail = FALSE)
  
  #Format Results 
  if (tau_p <= 0.01) {
    tau_hat = paste("$", round(tau_hat, 2), "^{***}$", sep = "")
  } else if (tau_p <= 0.05) {
    tau_hat = paste("$", round(tau_hat, 2), "^{**}$", sep = "")
  } else if (tau_p <= 0.1) {
    tau_hat = paste("$", round(tau_hat, 2), "^{*}$", sep = "")
  } else if (tau_p > 0.1) {
    tau_hat = paste("$", round(tau_hat, 2), "$", sep = "")
  }
  
  if (interaction_p <= 0.01) {
    interaction_hat = paste("$", round(interaction_hat, 2), "^{***}$", sep = "")
  } else if (interaction_p <= 0.05) {
    interaction_hat = paste("$", round(interaction_hat, 2), "^{**}$", sep = "")
  } else if (interaction_p <= 0.1) {
    interaction_hat = paste("$", round(interaction_hat, 2), "^{*}$", sep = "")
  } else if (interaction_p > 0.1) {
    interaction_hat = paste("$", round(interaction_hat, 2), "$", sep = "")
  }
  
  interaction_table = as.matrix(c(tau_hat, round(tau_t, 2), interaction_hat, round(interaction_t, 2)))
  
  return(list("tau_variance" = tau_variance, "interaction_variance" = interaction_variance, "tau_t" = tau_t, "interaction_t" = interaction_t,
              "tau_p" = tau_p, "interaction_p" = interaction_p, "interaction_table" = interaction_table))
  
}
```

#Estimate Effects 

#Mid-wage 

```{r}
covars = c("p_white_2010", "p_black_2010", "p_hispanic_2010", "p_asian_2010", "p_hs_pop_2010",
           "medianincome_2010", "medianrent_2010", "dist_cbd", "dist_hi",
           "p_nhood_college_pop_2010", "nta_medianincome_2010",
           "p_lesshs_pop_2010", "p_lesshs_laborforce_2010", "p_lesshs_unemp_2010",
           "p_hs_pop_2010", "p_hs_laborforce_2010", "p_hs_unemp_2010")
```

```{r}
mwlasso = rlasso(d_od_midwage_post ~ p_white_2010 + p_black_2010 + p_hispanic_2010 + p_asian_2010 + p_hs_pop_2010 +
                           medianincome_2010 + medianrent_2010 + dist_cbd + dist_hi +
                           p_nhood_college_pop_2010 + nta_medianincome_2010 + 
                           p_lesshs_pop_2010 + p_lesshs_laborforce_2010 + p_lesshs_unemp_2010 + 
                           p_hs_pop_2010 + p_hs_laborforce_2010 + p_hs_unemp_2010 + 
                           d_od_midwage_2002 + d_od_midwage_2003 + d_od_midwage_2004 + d_od_midwage_2005 + d_od_midwage_2006 + 
                           d_od_midwage_2007 + d_od_midwage_2009 + d_od_midwage_2010, 
                           data = post_data, intercept = FALSE, post = FALSE)
```

```{r}
selected_covars = intersect(covars, names(mwlasso$index[mwlasso$index == TRUE]))
```

```{r}
mw_lasso_data = nyc_data %>%
  filter(!if_any(all_of(selected_covars), is.na)) %>%
  filter(!if_any(all_of(selected_covars), is.nan)) %>%
  filter(!if_any(all_of(selected_covars), is.infinite)) %>%
  group_by(GEOID) %>%
  mutate(count = 1) %>%
  filter(sum(count) == 17) %>%
  select(-count) %>%
  ungroup()
```

```{r}
mw_covs = sdd.estimate(outcome = "d_od_midwage", treatment_var = "edugentrify", unit_var = "GEOID", time_var = "year", cluster_var = "NTA", 
                  time_pre = 2010, time_init = 2002, covariates = c("p_college_pop_2000", "p_college_pop_2010", 
                                                                    "d_w_midwage_2002", "d_w_midwage_2003", "d_w_midwage_2004", "d_w_midwage_2005", "d_w_midwage_2006",
                                                                    "d_w_midwage_2007", "d_w_midwage_2008", "d_w_midwage_2009", "d_w_midwage_2010"), 
                  cluster = FALSE, output_name = "mw_covs", data = nyc_data)
```
```{r}
mw_covs$tex_table
```

#Services 

```{r}
covars = c("p_white_2010", "p_black_2010", "p_hispanic_2010", "p_asian_2010", "p_hs_pop_2010",
           "medianincome_2010", "medianrent_2010", "dist_cbd", "dist_hi",
           "p_nhood_college_pop_2010", "nta_medianincome_2010",
           "p_lesshs_pop_2010", "p_lesshs_laborforce_2010", "p_lesshs_unemp_2010",
           "p_hs_pop_2010", "p_hs_laborforce_2010", "p_hs_unemp_2010")
```

```{r}
serviceslasso = rlasso(d_od_services_post ~ p_white_2010 + p_black_2010 + p_hispanic_2010 + p_asian_2010 + p_hs_pop_2010 +
                           medianincome_2010 + medianrent_2010 + dist_cbd + dist_hi +
                           p_nhood_college_pop_2010 + nta_medianincome_2010 + 
                           p_lesshs_pop_2010 + p_lesshs_laborforce_2010 + p_lesshs_unemp_2010 + 
                           p_hs_pop_2010 + p_hs_laborforce_2010 + p_hs_unemp_2010 + 
                           d_od_services_2002 + d_od_services_2003 + d_od_services_2004 + d_od_services_2005 + d_od_services_2006 + 
                           d_od_services_2007 + d_od_services_2009 + d_od_services_2010, 
                           data = post_data, intercept = FALSE, post = FALSE)
```

```{r}
selected_covars = intersect(covars, names(serviceslasso$index[serviceslasso$index == TRUE]))
```

```{r}
services_lasso_data = nyc_data %>%
  filter(!if_any(all_of(selected_covars), is.na)) %>%
  filter(!if_any(all_of(selected_covars), is.nan)) %>%
  filter(!if_any(all_of(selected_covars), is.infinite)) %>%
  group_by(GEOID) %>%
  mutate(count = 1) %>%
  filter(sum(count) == 17) %>%
  select(-count) %>%
  ungroup()
```

```{r}
services_covs = sdd.estimate(outcome = "d_od_services", treatment_var = "edugentrify", unit_var = "GEOID", time_var = "year", cluster_var = "NTA", 
                  time_pre = 2010, time_init = 2002, covariates = c("p_college_pop_2000", "p_college_pop_2010", selected_covars), cluster = FALSE, output_name = "services_covs",
                  data = services_lasso_data)
```

#Estimate Interactions 

```{r}
input = mw_covs$reg_data %>%
  spread.variables(variable = c("p_w_black"), years = c(2010, 2018), unit_var = "GEOID", time_var = "year") 
```

```{r}
mw_pc_white = plm(d_od_midwage ~ edugentrify + edugentrify*p_white_2010, model = "within", effect = "twoways", index = c("GEOID", "year"), weights = reg_weight, 
                  data = input)
``` 

```{r}
summary(mw_pc_white)
```

#Midwage Employment

```{r}
mw_white = plm(d_od_midwage ~ edugentrify + edugentrify*p_white_2010, model = "within", effect = "twoways", index = c("GEOID", "year"), weights = reg_weight, data = mw_covs$reg_data)
```

```{r}
mw_white_var = jackknife.interaction(outcome = "d_od_midwage", treatment_var = "edugentrify", interaction_var = "p_white_2010", unit_var = "GEOID", time_var = "year",
                                 tau_hat = mw_white$coefficients[1], interaction_hat = mw_white$coefficients[2], data = mw_covs$reg_data)
```

```{r}
mw_black = plm(d_od_midwage ~ edugentrify + edugentrify*p_black_2010, model = "within", effect = "twoways", index = c("GEOID", "year"), weights = reg_weight, data = mw_covs$reg_data)
```

```{r}
mw_black_var = jackknife.interaction(outcome = "d_od_midwage", treatment_var = "edugentrify", interaction_var = "p_black_2010", unit_var = "GEOID", time_var = "year",
                                 tau_hat = mw_black$coefficients[1], interaction_hat = mw_black$coefficients[2], data = mw_covs$reg_data)
```

```{r}
mw_hispanic = plm(d_od_midwage ~ edugentrify + edugentrify*p_hispanic_2010, model = "within", effect = "twoways", index = c("GEOID", "year"), weights = reg_weight, data = mw_covs$reg_data)
```

```{r}
mw_hispanic_var = jackknife.interaction(outcome = "d_od_midwage", treatment_var = "edugentrify", interaction_var = "p_hispanic_2010", unit_var = "GEOID", time_var = "year",
                                 tau_hat = mw_hispanic$coefficients[1], interaction_hat = mw_hispanic$coefficients[2], data = mw_covs$reg_data)
```

```{r}
mw_asian = plm(d_od_midwage ~ edugentrify + edugentrify*p_asian_2010, model = "within", effect = "twoways", index = c("GEOID", "year"), weights = reg_weight, data = mw_covs$reg_data)
```

```{r}
mw_asian_var = jackknife.interaction(outcome = "d_od_midwage", treatment_var = "edugentrify", interaction_var = "p_asian_2010", unit_var = "GEOID", time_var = "year",
                                 tau_hat = mw_asian$coefficients[1], interaction_hat = mw_asian$coefficients[2], data = mw_covs$reg_data)
```

#Services

```{r}
services_white = plm(d_od_services ~ edugentrify + edugentrify*p_white_2010, model = "within", effect = "twoways", index = c("GEOID", "year"), weights = reg_weight, 
                     data = services_covs$reg_data)
```

```{r}
services_white_var = jackknife.interaction(outcome = "d_od_services", treatment_var = "edugentrify", interaction_var = "p_white_2010", unit_var = "GEOID", time_var = "year",
                                 tau_hat = services_white$coefficients[1], interaction_hat = services_white$coefficients[2], data = services_covs$reg_data)
```

```{r}
services_black = plm(d_od_services ~ edugentrify + edugentrify*p_black_2010, model = "within", effect = "twoways", index = c("GEOID", "year"), weights = reg_weight, 
                     data = services_covs$reg_data)
```

```{r}
services_black_var = jackknife.interaction(outcome = "d_od_services", treatment_var = "edugentrify", interaction_var = "p_black_2010", unit_var = "GEOID", time_var = "year",
                                 tau_hat = services_black$coefficients[1], interaction_hat = services_black$coefficients[2], data = services_covs$reg_data)
```

```{r}
services_hispanic = plm(d_od_services ~ edugentrify + edugentrify*p_hispanic_2010, model = "within", effect = "twoways", index = c("GEOID", "year"), weights = reg_weight, 
                        data = services_covs$reg_data)
```

```{r}
services_hispanic_var = jackknife.interaction(outcome = "d_od_services", treatment_var = "edugentrify", interaction_var = "p_hispanic_2010", unit_var = "GEOID", time_var = "year",
                                 tau_hat = services_hispanic$coefficients[1], interaction_hat = services_hispanic$coefficients[2], data = services_covs$reg_data)
```

```{r}
services_asian = plm(d_od_services ~ edugentrify + edugentrify*p_asian_2010, model = "within", effect = "twoways", index = c("GEOID", "year"), weights = reg_weight, 
                     data = services_covs$reg_data)
```

```{r}
services_asian_var = jackknife.interaction(outcome = "d_od_services", treatment_var = "edugentrify", interaction_var = "p_asian_2010", unit_var = "GEOID", time_var = "year",
                                 tau_hat = services_asian$coefficients[1], interaction_hat = services_asian$coefficients[2], data = services_covs$reg_data)
```

#Report Outcomes

```{r}
mw_table = cbind(mw_white_var$interaction_table, mw_black_var$interaction_table, mw_hispanic_var$interaction_table, mw_asian_var$interaction_table)
```

```{r}
services_table = cbind(services_white_var$interaction_table, services_black_var$interaction_table, services_hispanic_var$interaction_table, services_asian_var$interaction_table)
```

```{r}
textable = xtable((mw_table), type = "latex")
print(textable, file = "/Users/liampurkey/Desktop/Honors/Results/Tables/New York/Tex/mw_race.tex", sanitize.text.function = function(x) x)
```

```{r}
textable = xtable((services_table), type = "latex")
print(textable, file = "/Users/liampurkey/Desktop/Honors/Results/Tables/New York/Tex/services_race.tex", sanitize.text.function = function(x) x)
```





